blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.PostList.as_view(), name="home"), # Home
    path('create_post/', views.create_post, name='create_post'), # Creates a new post
    path('<slug:slug>/edit/', views.edit_post, name='edit_post'), # Edit posts
    path('<slug:slug>/delete/', views.delete_post, name='delete_post'), # Delete Posts 
    path('submit-suggestion/', views.UserSuggestionView.as_view(), name='submit_suggestion'), # Send a new suggestion in the bottom of the page
    path('suggestion-like/<int:suggestion_id>/', views.SuggestionLike.as_view(), name='suggestion_like'), # Reaction to the suggestion
    path('suggestion-dislike/<int:suggestion_id>/', views.SuggestionDislike.as_view(), name='suggestion_dislike'), # Dislike in suggestion
    path('suggestion/edit/<int:suggestion_id>/', views.edit_suggestion, name='edit_suggestion'), # Edit Suggestion
    path('suggestion/delete/<int:suggestion_id>/', views.delete_suggestion, name='delete_suggestion'), # Delete Suggestion
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'), # Post main page with details
    path('like/<slug:slug>/', views.PostLike.as_view(), name='post_like'), # Like post
    path('comment-like/<int:comment_id>/', views.CommentLike.as_view(), name='comment_like'), # Like comment
    path('comment_dislike/<int:comment_id>/', views.CommentDislike.as_view(), name='comment_dislike'), # Dislike Comment
    path('sponsorship/contact/', views.sponsorship_contact, name='sponsorship_contact'), # Contact page
    path('sponsorship/thank-you/', views.sponsorship_thank_you, name='sponsorship_thank_you'), #Thank you page
]

buzzeirebrazil/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("", include("blog.urls"), name="blog-urls"),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Choices for the status of a blog post
STATUS = (
    (0, "Draft"),
    (1, "Published"),  # set to default
)


class Post(models.Model):
    """
    Represents a blog post in the system.

    Attributes:
        title (str): The title of the blog post.
        slug (str): An SEO-friendly URL for the post.
        author (User): The user who authored the post.
        featured_image (CloudinaryField): The featured image of the post.
        excerpt (str): A brief summary or excerpt of the post.
        updated_on (DateTime): The date and time of the last update.
        content (str): The main content of the blog post.
        created_on (DateTime): The date and time of creation.
        status (int): The status of the post (Draft or Published).
        likes (ManyToManyField): Users who have liked the post.
    """

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="blog_posts")
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=1)
    likes = models.ManyToManyField(User, related_name='blogpost_like',
                                   blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        """Returns the total number of likes for this post."""
        return self.likes.count()


class Comment(models.Model):
    """
    Represents a comment made on a blog post.

    Attributes:
        post (Post): The blog post the comment is linked to.
        name (str): The name of the commenter.
        email (Email): The email of the commenter.
        body (str): The main content of the comment.
        created_on (DateTime): The date and time of creation.
        approved (bool): Indicates whether the comment is approved.
        likes (ManyToManyField): Users who have liked the comment.
        dislikes (ManyToManyField): Users who have disliked the comment.
    """

    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    likes = models.ManyToManyField(User, related_name='comment_likes',
                                   blank=True)
    dislikes = models.ManyToManyField(User, related_name='disliked_comments',
                                      blank=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"


class UserSuggestion(models.Model):
    """
    Represents a user's suggestion.

    Attributes:
        user (User): The user who made the suggestion.
        suggestion_text (str): The text of the suggestion.
        likes (ManyToManyField): Users who have liked the suggestion.
        dislikes (ManyToManyField): Users who have disliked the suggestion.
        created_on (DateTime): The date and time of creation.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    suggestion_text = models.TextField()
    likes = models.ManyToManyField(User, related_name='suggestion_likes')
    dislikes = models.ManyToManyField(User, related_name='suggestion_dislikes')
    created_on = models.DateTimeField(auto_now_add=True)

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

    @classmethod
    def total_suggestions(cls):
        return cls.objects.count()


class Suggestion(models.Model):
    """
    Represents a suggestion made by a user.

    Attributes:
        user (User): The user who made the suggestion.
        suggestion_text (str): The text of the suggestion.
        created_on (DateTime): The date and time of creation.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    suggestion_text = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="{% static 'static/favicon.ico' %}" type="image/x-icon">
    <script src="https://kit.fontawesome.com/35b1c3ec6c.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Blocks for extra styles and scripts specific to individual pages -->
    
    {% block extra_styles %}{% endblock %}
    {% block extra_scripts %}{% endblock %}

     <title>BuzzEireBrazil - Your Bridge in Ireland</title>

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    {% include "navbar.html" %}

    <!-- Create Post Button -->
    {% include "create_post_button.html" %}

    <!-- Page Content Container -->
    <div class="container-fluid mt-4">
        <div class="row">
            {% include "sidebar.html" %}


            <!-- Main Content -->
            <div class="col-md-8">
                <main class="flex-shrink-0 main-bg">
                    {% block content %}
                    <!-- Cards and suggestion -->
                    {% endblock content %}
                </main>
            </div>
        </div>
    </div>

    <!-- Footer -->
    {% include "footer.html" %}

    <!-- Load the Bootstrap's JS script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
</body>

</html>

templates/create_post_button.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>

<title>create post button</title>

</head>

<!-- Create Post Button -->
<div class="row">
    <div class="col-md-4 d-flex justify-content-center mt-2 d-lg-none">
        <a id="create-post-link-1"
            href="{% if user.is_authenticated %}{% url 'create_post' %}{% else %}{% url 'account_login' %}?next={% url 'create_post' %}{% endif %}"
            class="btn btn-success">
            {% if user.is_authenticated %}
            <i class="fa-solid fa-plus"></i> Create a new Post
            {% else %}
            <i class="fas fa-sign-in-alt"></i> Login
            {% endif %}
        </a>
    </div>
</div>

templates/footer.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>

<title>Footer</title>

</head>

<!-- Footer -->
<footer class="footer mt-auto py-3 dark-bg">
    <p class="m-0 text-center text-white">Felipe Zanetti 2023</p>
    <p class="m-0 text-center text-white">Get connected with me: 
        <a href="https://www.linkedin.com/in/felipe-zanetti/" aria-label="LinkedIn Profile">
            <i class="fab fa-linkedin ms-3 white-icon"></i>
        </a>
        <a href="https://github.com/zanettiprado" aria-label="GitHub Profile">
            <i class="fab fa-github ms-3 white-icon"></i>
        </a>
    </p>
</footer>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Home - BuzzEireBrazil</title>
</head>
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% include "welcome.html" %}

<div class="container mt-5 mx-auto">
    <a id="create-post-link"
        href="{% if user.is_authenticated %}{% url 'create_post' %}{% else %}{% url 'account_login' %}?next={% url 'create_post' %}{% endif %}"
        class="btn btn-success col-md-3 mx-auto d-none d-lg-block ">
        {% if user.is_authenticated %}
        <i class="fa-solid fa-plus"></i> Create a new Post
        {% else %}
        <i class="fas fa-sign-in-alt"></i> Login
        {% endif %}
    </a>

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4 mt-2">
                    <div class="card mb-4 card-green-orange">
                        <div class="card-body">
                            <div class="image-container">
                                <!-- Featured Image -->
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://www.edublin.com.br/wp-content/uploads/2021/07/Green_harp_flag_of_Ireland_17th_century.svg-660x440.png"
                                    alt="Standart picture for any post">
                                {% else %}
                                <img class="card-img-top" src="{{ post.featured_image.url }}"
                                    alt="Main image of the post">
                                {% endif %}
                                <div class="image-flash">
                                    <!-- Author Information -->
                                    <p class="author">{{ post.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                <!-- Post Title and Excerpt -->
                                <h2 class="card-title-index">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>
                            <hr/>
                            <!-- Post Created Date and Likes ------------------------->
                            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
                                {{ post.number_of_likes }}</p>

                            <!-- Post Edit and Delete opition ------------------------->
                            {% if user.is_authenticated and user == post.author or user.is_staff %}
                            <a href="{% url 'edit_post' post.slug %}" class="btn btn-sm btn-warning">
                                <i class="fas fa-edit"></i> Edit
                            </a>
                            <a href="{% url 'delete_post' post.slug %}" class="btn btn-sm btn-danger">
                                <i class="fas fa-trash-alt"></i> Delete
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link btn-success">&laquo; PREV </a>
                </li>
                {% endif %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="page-link btn-success"> NEXT &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
        <br>
    </div>
</div>

<!-- User Suggestion Section -->
<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-md-12">
            <!-- Suggestion Form -->
            <h3 class="sub-title">What would you like to see here at <strong>BuzzEireBrazil</strong>?</h3>

            <!-- Suggestion form for authenticated users -->
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'submit_suggestion' %}">
                {% csrf_token %}
                {{ suggestion_form.suggestion_text.label_tag }}
                <textarea name="suggestion_text" id="id_suggestion_text" rows=""
                    cols="20">{{ suggestion_form.suggestion_text.value|default:"" }}</textarea>

                <button type="submit" class="btn btn-success mt-1" aria-label="submit suggestion">Submit</button>
                {% if suggestion_form.errors.suggestion_text %}
                <p class="error">{{ suggestion_form.errors.suggestion_text }}</p>
                {% endif %}
            </form>
            {% else %}
            <!-- User is not logged in, suggest them to log in -->
            <div class="alert alert-info" role="alert">
                Please <a href="{% url 'account_login' %}" class="btn btn-success col-md-2">
                    <i class="fas fa-sign-in-alt"></i> &nbsp;log in
                </a> to leave a suggestion.
            </div>
            {% endif %}

            <!-- Suggestions List -->
            <ul class="list-group mt-4 suggestions-list">
                {% for suggestion in suggestions %}
                <li class="list-group-item suggestion-item">
                    <div class="suggestion-text user-suggestion-text">
                        <strong>{{ suggestion.suggestion_text }}</strong>
                    </div>
                    <div class="suggestion-details text-success">
                        Suggested by {{ suggestion.user.username }} on {{ suggestion.created_on }}
                    </div>
                    <div class="suggestion-actions mt-2">
                        <!-- Like button for suggestions -->
                        <form class="d-inline" action="{% url 'suggestion_like' suggestion.id %}" method="POST">
                            {% csrf_token %}
                            {% if user.is_authenticated %}
                            {% if user in suggestion.likes.all %}
                            <button type="submit" name="liked" value="unliked" class="btn-like"
                                aria-label="Liked button"><i class="fas fa-thumbs-up"></i></button>
                            {% else %}
                            <button type="submit" name="liked" value="liked" class="btn-like"><i
                                    class="far fa-thumbs-up" aria-label="Liked button"></i></button>
                            {% endif %}
                            {% else %}
                            <button type="submit" name="liked" value="liked" class="btn-like" disabled><i
                                    class="far fa-thumbs-up" aria-label="Liked button"></i></button>
                            {% endif %}
                        </form>
                        <span class="likes">{{ suggestion.total_likes }}</span>
                        <!-- Dislike button for suggestions -->
                        <form class="d-inline" action="{% url 'suggestion_dislike' suggestion.id %}" method="POST">
                            {% csrf_token %}
                            {% if user.is_authenticated %}
                            {% if user in suggestion.dislikes.all %}
                            <button type="submit" name="disliked" value="undisliked" class="btn-dislike"><i
                                    class="fas fa-thumbs-down" aria-label="Disliked button"></i></button>
                            {% else %}
                            <button type="submit" name="disliked" value="disliked" class="btn-dislike"><i
                                    class="far fa-thumbs-down" aria-label="Disliked button"></i></button>
                            {% endif %}
                            {% else %}
                            <button type="submit" name="disliked" value="disliked" class="btn-dislike" disabled><i
                                    class="far fa-thumbs-down" aria-label="Disliked button"></i></button>
                            {% endif %}
                        </form>
                        <span class="dislikes">{{ suggestion.total_dislikes }}</span>

                        <!-- Edit and Delete buttons for suggestions -->
                        {% if user.is_authenticated %}
                        {% if user == suggestion.user or user.is_staff %}
                        <a href="{% url 'edit_suggestion' suggestion.id %}" class="btn btn-sm btn-warning">
                            <i class="fas fa-edit"></i> Edit
                        </a>
                        <a href="{% url 'delete_suggestion' suggestion.id %}" class="btn btn-sm btn-danger">
                            <i class="fas fa-trash-can"></i> Delete</i>
                        </a>
                        {% endif %}
                        {% endif %}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<script>
    // Set the suggested text for users in the textarea
    document.addEventListener('DOMContentLoaded', function () {
        var suggestionText = document.getElementById('id_suggestion_text');

        suggestionText.value = 'What can you suggest today?';
        suggestionText.style.color = 'gray';

        suggestionText.addEventListener('focus', function () {
            if (this.value === 'What can you suggest today?') {
                this.value = '';
            }
            this.style.color = 'black';
        });

        suggestionText.addEventListener('blur', function () {
            if (this.value === '') {
                this.value = 'What can you suggest today?';
                this.style.color = 'gray';
            }
        });
    });
</script>
{% endblock content %}

templates/navbar.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>

<title>Navigation bar</title>

</head>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
        <!-- Brand Logo -->
        <a class="navbar-brand logo" href="{% url 'home' %}">
            <span class="brand">Buzz<span class="red-o">Eire</span>Brazil</span>
        </a>
        <!-- Mobile Navigation Toggle Button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navigation Links -->
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active font-weight-bold" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="{% url 'account_signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="{% url 'account_login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>

        <!-- User Greeting -->
        {% if user.is_authenticated %}
        <span class="navbar-text">
            Welcome, <strong>{{ user.username }}!</strong>
        </span>
        <br>
        {% endif %}
    </div>
</nav>

templates/post_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Post - Details</title>
</head>
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<div class="container mb-3">
    <!-- Return button -->
    <div class="col-md-12 mb-3">
        <div class="row">{% include "return_button.html" %}</div>
    </div>
    <div class="row justify-content-start">
        <div class="col-md-12">
            <div class="card card-green-orange mb-4" style="width: 100%;">
                <div class="card-header bg-orange">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="text-dark">{{ post.author }} | {{ post.created_on }}</p>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            {% if "placeholder" in post.featured_image.url %}
                            <img src="https://www.edublin.com.br/wp-content/webp-express/webp-images/uploads/2017/07/shutterstock_265691192.jpg.webp"
                                class="img-fluid mb-3" style="width: 100%;" alt="Regular image if they miss">
                            {% else %}
                            <img src="{{ post.featured_image.url }}" class="img-fluid mb-3" style="width: 100%;">
                            {% endif %}
                        </div>
                        <div class="col-md-6">
                            <p>{{ post.content | safe }}</p>
                        </div>
                    </div>
                    <!-- like post  -->
                    <div class="row mt-3">
                        <div class="col-2">
                            <strong>
                                {% if user.is_authenticated %}
                                <form class="d-inline" action="{% url 'post_like' post.slug %}" method="POST">
                                    {% csrf_token %}
                                    {% if liked %}
                                    <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"
                                        aria-label="submit-like-button"><i
                                            class="fas fa-heart text-danger"></i></button>
                                    {% else %}
                                    <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"
                                        aria-label="submit-like-button"><i class="far fa-heart"></i></button>
                                    {% endif %}
                                </form>
                                {% else %}
                                <span class="text-secondary"><i class="far fa-heart"></i></span>
                                {% endif %}
                                <span class="text-secondary">{{ post.number_of_likes }} </span>
                            </strong>
                        </div>
                        <div class="col-2">
                            {% with comments.count as total_comments %}
                            <strong class="text-secondary"><i class="far fa-comments text-info"></i>
                                {{ total_comments }}</strong>
                            {% endwith %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 card mb-4 mt-3">
            <h3 class="card-header bg-success">Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="text-danger">{{ comment.name }} <small
                                class="text-dark">{{ comment.created_on }}</small></h5>
                        <p class="card-text">{{ comment.body | linebreaks }}</p>

                        <!-- like comment -->
                        <div class="comment-like">
                            <strong class="text-secondary"><i class="far fa-thumbs-up"></i> <span
                                    id="comment-likes-count-{{ comment.id }}">{{ comment.likes.count }}</span></strong>
                            <br>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'comment_like' comment.id %}" method="POST">
                                {% csrf_token %}
                                {% if user in comment.likes.all %}
                                <button type="submit" name="liked" value="unliked" class="btn-like liked"
                                    aria-label="submit-button"><i class="fas fa-thumbs-up"></i></button>
                                {% else %}
                                <button type="submit" name="liked" value="liked" class="btn-like"
                                    aria-label="submit-button"><i class="far fa-thumbs-up"></i></button>
                                {% endif %}
                            </form>
                            <span class="like-count col-2">{{ comment.likes.count }}</span>
                            {% endif %}

                            <!-- Dislike button (only for authenticated users) -->
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'comment_dislike' comment.id %}" method="POST">
                                {% csrf_token %}
                                {% if user in comment.dislikes.all %}
                                <button type="submit" name="disliked" value="undisliked" class="btn-dislike disliked"
                                    aria-label="submit-dislike-button"><i class="fas fa-thumbs-down"></i></button>
                                {% else %}
                                <button type="submit" name="disliked" value="disliked" class="btn-dislike"
                                    aria-label="submit-dislike-button"><i class="far fa-thumbs-down"></i></button>
                                {% endif %}
                            </form>
                            <span class="dislike-count">{{ comment.dislikes.count }}</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- approval for comments -->
    <div class="row">
        <div class="col-md-12 card mb-4 mt-3">
            <div class="card-body">
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}
                <h3 class="card-header bg-success">Leave a Comment:</h3>
                <p class="mt2">Posting as:&nbsp; {{ user.username }}</p>
                <form method="post">
                    <label for="post">Comment:</label>
                    <br>
                    {{comment_form}}
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4 d-flex left mt-3">
                            <button type="submit" class="btn btn-success" aria-label="submit-button"> <i
                                    class="fa fa-arrow-circle-right fa-lg"></i>&nbsp;&nbsp;Submit</button>
                        </div>
                    </div>
                </form>
                {% else %}
                <!-- User is not logged in, suggest them to log in -->
                <div class="alert alert-info" role="alert">
                    Please <a href="{% url 'account_login' %}" class="btn btn-success col-md-2"><i
                            class="fas fa-sign-in-alt"></i> &nbsp;log in</a> to leave
                    a comment.
                </div>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/return_button.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>

<title>Return button</title>

</head>

<div class="col-md-4 text-right">
    <a href="{% url 'home' %}" class="btn btn-success rounded">
        <i class="fas fa-home" aria-label="Delete Post"></i> Return
    </a>
</div>